# Numpy in Python

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
# create 1-D array
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# create 2-D array (Collections of 1-D array)
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
# create array of zeros by providing rows and columns in it
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# create array of regulater interval values, arange(start,stop,difference)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
# create evenly spaced numbers over a specified interval, linspace(start,stop,no.of values to be generated)
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [3]:
# create set of arrays each element is represent by row as well as columns
np.indices((3,2))

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 1],
        [0, 1],
        [0, 1]]])