# Numpy in Python

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
# create 1-D array
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# create 2-D array (Collections of 1-D array)
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
# create array of zeros by providing rows and columns in it
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# create array of regulater interval values, arange(start,stop,difference)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
# create evenly spaced numbers over a specified interval, linspace(start,stop,no.of values to be generated)
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [3]:
# create set of arrays of each element is represent in row as well as columns
np.indices((3,2))

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 1],
        [0, 1],
        [0, 1]]])

In [4]:
# Datatype of array
a = np.array([1,2,3])
print(a.dtype)   # shows data type of elements which are stores inside numpy array

int32


1) Compair Memory for list and numpy arrays:

In [27]:
l = range(1000)
a = 1
import sys # module inside python to calculate size
print(sys.getsizeof(a))    # getsizeof() calculate size of particular predefined data type (e.g int,float,char)
print(len(l))              # calculate size of list
print("Memory taken by list is:",sys.getsizeof(a) * len(l)) # Determines total memory size in bytes taken by list


28
1000
Memory taken by list is: 28000


In [28]:
a = np.arange(1000)
print(a.itemsize)  # itemsize property calculate memory size of individual element inside array
print(a.size)      # size property calculate size of array
print("Memory taken by numpy array is:",a.size * a.itemsize) # Determines total memory size in bytes taken by numpy array

4
1000
Memory taken by numpy array is: 4000


2) Compair Speed for list and numpy arrays:

In [29]:
import time # module inside python to check speed
import sys  #  module inside python to calculate size

size = 1000000
l1=range(size)
l2=range(size)

start = time.time()  # before operation on list start timer using 'time' module
result = [(x+y) for x,y in zip(l1,l2)]  # list operation
print("Time taken by list operation is:",(time.time() - start)*1000) 
# substracting start time from current time will give time(in microsecond) taken by list operation


Time taken by list operation is: 135.3132724761963


In [30]:
n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()  
result = n1+n2     # Numpy array operation
print("Time taken by Numpy array operation is:",(time.time() - start)*1000) 

Time taken by Numpy array operation is: 16.92986488342285


3) Convinient to use Numpy arrays than list because we can do the big calcuations easily without writing any loops and anything

# Numpy Operations

In [33]:
a = np.array([[1,2,3],[4,5,6]]) # 2-D array
print(a.ndim)                   # ndim property will give the dimension of particular array

2


In [34]:
print(a.itemsize)  # itemsize property calculate memory size of individual element inside array

4


In [35]:
print(a.dtype)  # shows data type of elements which are stores inside numpy array

int32


In [36]:
print(a.shape)  # shape property gives no. of rows and no. of coloumns in numpy array

(2, 3)


In [37]:
print(a.size)  # size property give total no. of elements inside the numpy array

6


### Reshape Function (when we want to change No. of rows and coloumns of already defined Numpy array then this function used)

In [41]:
print("Before:",a.shape)
a = a.reshape(3,2) # np.reshape(a,(3,2))
print("After:",a.shape)

Before: (2, 3)
After: (3, 2)


### Slicing and Indexing

In [42]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

Indexing access only one element at a time form array

In [43]:
a[0,0]

1

In [72]:
# If we want 2 and 5 elemnts only from array
a[[0,2],[1,0]]  # a[[put rows index],[put columns index]]

array([2, 5])

Slicing access set of elements at a time from array (we can do slicing on both row as well as coloumns)

In [46]:
print(a[0:,1]) # a[row slicing,coloumn slicing]
print(a[1,1:])

[2 4 6]
[4]


In [48]:
print("Minimum value in array is:",a.min()) # min element in Numpy array
print("Maximum value in array is:",a.max()) # max element in Numpy array
print("Totalsum of values in array is:",a.sum()) # Total sum of elements in Numpy array

Minimum value in array is: 1
Maximum value in array is: 6
Totalsum of values in array is: 21


In [50]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
print(np.sum(a, axis=0))  # calculate coulumns sum
print(np.sum(a, axis=1))  # calculate rows sum

[ 9 12]
[ 3  7 11]


# Numpy Array Mathematical Opearations

In [67]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print("X is:\n",x,"\n")
print("y is:\n",y,"\n")

print("Addition of two array is:\n",np.add(x,y)) # (x+y) 

print("sutraction of two array is:\n",np.subtract(x,y)) # (x-y)

print("Multiplication of two array is:\n",np.multiply(x,y)) # (x*y)

print("Dividation of two array is:\n",np.divide(x,y)) # (x/y)

print("Square root of 1st array is:\n",np.sqrt(x))



X is:
 [[1 2]
 [3 4]] 

y is:
 [[5 6]
 [7 8]] 

Addition of two array is:
 [[ 6  8]
 [10 12]]
sutraction of two array is:
 [[-4 -4]
 [-4 -4]]
Multiplication of two array is:
 [[ 5 12]
 [21 32]]
Dividation of two array is:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Square root of 1st array is:
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [71]:
print("2-D array:",a.ndim)
print(a.flatten())   # flatten() Return a copy of the array collapsed into one dimension.
print("1-D array:",a.ndim) 

2-D array: 2
[1 2 3 4 5 6]
1-D array: 2
