### Registration ID : GO_STP_9654

1) Import the numpy package under the name np and Print the numpy version and the configuration 

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Lenovo/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

2) Create a null vector of size 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Create Simple 1-D array and check type and check data types in array

In [4]:
n1 = np.arange(1,20,2)
print(n1)
print(type(n1))
print(n1.dtype)

[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>
int32


4) How to find number of dimensions, bytes per element and bytes of memory used?

In [5]:
n1 = np.array([['a','b','c','d']])
print(n1)
print(n1.ndim)
print(n1.itemsize)
print(n1.nbytes)


[['a' 'b' 'c' 'd']]
2
4
16


5) Create a null vector of size 10 but the fifth value which is 1

In [6]:
n1 = np.zeros(10)
n1[4]=1
print(n1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6) Create a vector with values ranging from 10 to 49

In [7]:
n1 = np.arange(10,49)
print(n1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


7) Reverse a vector (first element becomes last)

In [8]:
n1 = np.arange(10,49)
print(n1[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


8) Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
n1 = np.arange(0,9)
n1.reshape(3,3)
print(np.eye(3,3))
print(n1.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1


9) Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
n1 = np.array([1,2,0,0,4,0])
np.nonzero(n1)

(array([0, 1, 4], dtype=int64),)

10) Create a 3x3 identity matrix

In [18]:
# identity(n, dtype = None) Returns identity array of dimension n x n,with its main diagonal set to one,
# and all other elements 0.

np.identity(3,dtype=int) 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
# eye(R, C = None, k = 0, dtype = type <‘float’> )Returns array of shape, R x C, an array where all elements are equal to zero,
# except for the k-th diagonal,whose values are equal to one.

np.eye(3,3,k=0,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

11) Create a 3x3x3 array with random values

In [12]:
np.random.random((3, 3, 3))

array([[[0.79558048, 0.43057327, 0.16299861],
        [0.25607401, 0.32059415, 0.88320877],
        [0.92942366, 0.08857512, 0.59300009]],

       [[0.74934821, 0.33020095, 0.71533119],
        [0.20224847, 0.85141235, 0.64583194],
        [0.43987667, 0.77862008, 0.18328104]],

       [[0.23617048, 0.9297678 , 0.19672945],
        [0.8768309 , 0.07642402, 0.49465679],
        [0.31322344, 0.57476468, 0.2623683 ]]])

12) Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
n1 = np.random.random((10, 10, 10))
print(np.max(n1))
print(np.min(n1))

0.9998285883701168
0.0020363096018092275


13) Create a random vector of size 30 and find the mean value

In [26]:
v = np.random.random((5,6))
np.mean(v)

0.5189991694245529

14) Create a 2d array with 1 on the border and 0 inside

In [27]:
n1 = np.ones((5,5))
n1[1:4, 1:4]=0
print(n1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


15) How to add a border (filled with 0's) around an existing array?

In [28]:
n1 = np.ones((5,5))
n1[:,:1]=0
n1[:1,:]=0
n1[:,4:]=0
n1[4:,:]=0
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


16) How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [36]:
n1 = np.arange(1,15).reshape(2,7)
print(n1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [38]:
n1[1,5] # to get 13 n1[1][5]

13

In [43]:
n1[:1,:] # to get first row only

array([[1, 2, 3, 4, 5, 6, 7]])

In [44]:
n1[:,2] # to get 3rd column only

array([ 3, 10])

In [46]:
n1[:1,1:7:2] # to get [2, 4, 6]

array([[2, 4, 6]])

In [50]:
n1[1,5]=20 # to replace 13 by 20
n1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

17) How to Convert a 1D array to a 2D array with 2 rows

In [55]:
n1 = np.arange(1,11)
print(n1)
print(n1.ndim)
n2 = n1.reshape(5,2)
print(n2)
print(n2.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


In [57]:
a = np.array([1,2,3])
np.append(np.repeat(a,3), np.tile(a,3))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

repeat(arr, repetitions, axis = None) Return :

An array with repetitions of array - arr elements as per repetitions, number of times 
we want to repeat arr  

tile(arr, repetitions) Return :

An array with repetitions of array - arr as per d, number of times we want to repeat arr

19) Write a program to show how Numpy taking less memory compared to Python List?

In [60]:
l = range(100)

a = 2

import sys

# Size of Python list

list_size = (sys.getsizeof(a) * len(l))
print("list_size:",list_size)

# Size of numpy array

al = np.arange(100)

numpy_size = (al.size * al.itemsize)
print("numpy_size:",numpy_size)

list_size: 2800
numpy_size: 400


20) Write a program to show how Numpy taking less time compared to Python List?

In [61]:
import time

import sys

# Python List

size = 10000000

l1 = range(size)

l2 = range(size)

start = time.time()

result = [(x * y) for x,y in zip(l1, l2)]

print("Time taken by List: ", (time.time() - start), "seconds")

# Numpy Array

nl1 = np.arange(size)

nl2 = np.arange(size)

start1 = time.time()

res = nl1 * nl2

print("Time taken by numpy array: ", (time.time() - start1), "seconds")

Time taken by List:  1.198376178741455 seconds
Time taken by numpy array:  0.030880451202392578 seconds
